from typing import Sequence, Protocol
from app.domain.broadcasts.entities import Broadcast, BroadcastStatus

class IBroadcastRepository(Protocol):
    async def create(self, broadcast: Broadcast) -> Broadcast: ...
    async def get_by_id(self, id: int) -> Broadcast | None: ...
    async def list_broadcasts(self, skip: int = 0, limit: int = 20) -> tuple[Sequence[Broadcast], int]: ...
    async def update_status(self, id: int, status: BroadcastStatus) -> Broadcast | None: ...
    async def increment_counts(self, id: int, sent: int = 0, failed: int = 0) -> None: ...
