"""API v1 — Movies endpoints.  Phase 1: CRUD + search."""
from typing import Sequence
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status, UploadFile, File, Form
import logging
from pydantic import BaseModel, Field, computed_field

logger = logging.getLogger(__name__)

from app.api.deps import get_movie_service, get_current_admin
from app.application.movies.service import MovieService
from app.domain.movies.entities import Movie
from app.api.v1.categories import CategoryResponse
from app.api.v1.pages import PageResponse
from app.infrastructure.telegram.telegram_client import telegram_client
from app.utils.telegram_link_parser import parse_telegram_link

router = APIRouter(prefix="/movies", tags=["movies"])


# ── Schemas ──────────────────────────────────────────────────────
class MovieCreate(BaseModel):
    title: str
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = Field(None, ge=0, le=10)
    tmdb_rating: float | None = Field(None, ge=0, le=10)
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    code: str | None = None # Autogenerated if missing
    category_ids: list[int] | None = None
    page_ids: list[int] | None = None
    source_link: str | None = None

class MovieUpdate(BaseModel):
    title: str | None = None
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = Field(None, ge=0, le=10)
    tmdb_rating: float | None = Field(None, ge=0, le=10)
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    category_ids: list[int] | None = None
    page_ids: list[int] | None = None
    source_link: str | None = None

class MovieTranslationResponse(BaseModel):
    id: int
    movie_id: int
    language: str
    telegram_file_id: str | None = None
    storage_channel_message_id: int | None = None
    
    model_config = {"from_attributes": True}

class MovieResponse(BaseModel):
    id: int
    title: str
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = None
    tmdb_rating: float | None = None
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    code: str
    categories: list[CategoryResponse] = []
    pages: list[PageResponse] = []
    translations: list[MovieTranslationResponse] = []

    source_chat_id: int | None = None
    source_topic_id: int | None = None

    @computed_field
    def source_link(self) -> str | None:
        if self.source_chat_id:
            chat_id_str = str(self.source_chat_id).replace("-100", "")
            if self.source_topic_id:
                return f"https://t.me/c/{chat_id_str}/{self.source_topic_id}"
            return f"https://t.me/c/{chat_id_str}"
        return None

    model_config = {"from_attributes": True}

class PaginatedMoviesResponse(BaseModel):
    items: list[MovieResponse]
    total: int


# ── Endpoints ────────────────────────────────────────────────────
@router.post("", response_model=MovieResponse, status_code=status.HTTP_201_CREATED)
async def create_movie(
    movie_in: MovieCreate,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Create a new movie (Admin only)."""
    data = movie_in.model_dump()
    source_link = data.pop("source_link", None)
    
    if source_link:
        try:
            parsed = parse_telegram_link(source_link)
            data["source_chat_id"] = parsed["chat_id"]
            data["source_topic_id"] = parsed["topic_id"]
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))
            
    return await service.create_movie(**data)


@router.get("", response_model=PaginatedMoviesResponse)
async def list_movies(
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    category_id: int | None = None,
    page_id: int | None = None,
    service: MovieService = Depends(get_movie_service)
):
    """List movies, optionally filtered by category (Public)."""
    movies, total = await service.list_movies(skip=skip, limit=limit, category_id=category_id, page_id=page_id)
    return {"items": movies, "total": total}


@router.get("/search", response_model=PaginatedMoviesResponse)
async def search_movies(
    q: str = Query(..., min_length=2),
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    service: MovieService = Depends(get_movie_service)
):
    """Search movies by title (Public)."""
    movies, total = await service.search_movies(title_query=q, skip=skip, limit=limit)
    return {"items": movies, "total": total}


@router.get("/{movie_id}", response_model=MovieResponse)
async def get_movie(
    movie_id: int,
    service: MovieService = Depends(get_movie_service)
):
    """Get movie by ID (Public)."""
    movie = await service.get_movie(movie_id)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found")
    return movie


@router.get("/code/{code}", response_model=MovieResponse)
async def get_movie_by_code(
    code: str,
    service: MovieService = Depends(get_movie_service)
):
    """Get movie by unique code (Public / used by bot deep link)."""
    movie = await service.get_movie_by_code(code)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found")
    return movie


@router.put("/{movie_id}", response_model=MovieResponse)
async def update_movie(
    movie_id: int,
    movie_in: MovieUpdate,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Update a movie (Admin only)."""
    data = movie_in.model_dump(exclude_unset=True)
    source_link = data.pop("source_link", None)
    
    if source_link:
        try:
            parsed = parse_telegram_link(source_link)
            data["source_chat_id"] = parsed["chat_id"]
            data["source_topic_id"] = parsed["topic_id"]
        except ValueError as e:
            raise HTTPException(status_code=400, detail=str(e))
    elif "source_link" in movie_in.model_fields_set and source_link is None:
        data["source_chat_id"] = None
        data["source_topic_id"] = None
        
    movie = await service.update_movie(movie_id=movie_id, **data)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found")
    return movie


@router.post("/{movie_id}/upload-video", response_model=MovieResponse)
async def upload_movie_video(
    movie_id: int,
    request: Request,
    file: UploadFile = File(...),
    language: str = Form("Asosiy"),
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Upload video for a movie to Telegram storage (Admin only)."""
    MAX_SIZE = 50 * 1024 * 1024  # 50 MB

    if not file.content_type or not file.content_type.startswith("video/"):
        raise HTTPException(status_code=400, detail="Faqat video fayllar ruxsat etiladi (MIME turi video/* bo'lishi kerak).")

    # 1. Content-Length header tekshiruvi (agar server yuborsa)
    content_length = request.headers.get("content-length")
    if content_length:
        try:
            if int(content_length) > MAX_SIZE:
                raise HTTPException(status_code=413, detail="Fayl hajmi 50MB dan oshmasligi kerak.")
        except ValueError:
            pass  # Invalid Content-Length — chunked o'qishda tekshiramiz

    # 2. Chunked o'qish — xotirani to'ldirmaslik uchun
    chunks = []
    total_size = 0
    async for chunk in file:
        total_size += len(chunk)
        if total_size > MAX_SIZE:
            raise HTTPException(status_code=413, detail="Fayl hajmi 50MB dan oshmasligi kerak.")
        chunks.append(chunk)
    file_bytes = b"".join(chunks)

    try:
        file_id, message_id = await telegram_client.send_video_to_storage(
            file_bytes=file_bytes,
            filename=file.filename or "video.mp4",
            mime_type=file.content_type
        )
    except Exception as e:
        logger.error(f"Error in upload_movie_video endpoint for movie {movie_id}: {str(e)}", exc_info=True)
        raise

    movie = await service.add_movie_translation(
        movie_id=movie_id,
        language=language,
        file_id=file_id,
        message_id=message_id
    )

    if not movie:
        raise HTTPException(status_code=404, detail="Kino topilmadi.")

    return movie


class LinkVideoRequest(BaseModel):
    message_id: int
    language: str = "Asosiy"

@router.post("/{movie_id}/link-video", response_model=MovieResponse)
async def link_movie_video(
    movie_id: int,
    request: LinkVideoRequest,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Link video for a movie from an existing message ID in the storage channel (Admin only)."""
    try:
        movie = await service.link_movie_video_from_message(movie_id, request.message_id, request.language)
        if not movie:
            raise HTTPException(status_code=404, detail="Movie not found")
        return movie
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in link_movie_video endpoint for movie {movie_id}: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Xabardan video olishda kutilmagan xatolik.")

@router.delete("/translations/{translation_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_movie_translation(
    translation_id: int,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Delete a movie translation (Admin only)."""
    success = await service.delete_movie_translation(translation_id)
    if not success:
        raise HTTPException(status_code=404, detail="Translation not found")

@router.delete("/{movie_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_movie(
    movie_id: int,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Delete a movie (Admin only)."""
    success = await service.delete_movie(movie_id)
    if not success:
        raise HTTPException(status_code=404, detail="Movie not found")
