"""API v1 — Movies endpoints.  Phase 1: CRUD + search."""
from typing import Sequence
from fastapi import APIRouter, Depends, HTTPException, Query, Request, status, UploadFile, File, Form
import logging
import asyncio
import os
import tempfile
from datetime import datetime
from pydantic import BaseModel, Field, computed_field

logger = logging.getLogger(__name__)

from app.api.deps import get_movie_service, get_current_admin, get_admin_or_bot, get_db_session
from sqlalchemy.ext.asyncio import AsyncSession
from app.application.movies.service import MovieService
from app.domain.movies.entities import Movie
from app.api.v1.categories import CategoryResponse
from app.api.v1.pages import PageResponse
from app.infrastructure.telegram.telegram_client import telegram_client
from app.utils.telegram_link_parser import parse_telegram_link
from app.core.job_manager import job_manager, JobStatus
from app.api.limiter import limiter
from app.utils.trailer import validate_and_normalize_trailer_url
from app.core.cache import get_cache, set_cache, delete_cache_pattern

router = APIRouter(prefix="/movies", tags=["movies"])


# ── Schemas ──────────────────────────────────────────────────────
class MovieCreate(BaseModel):
    title: str
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = Field(None, ge=0, le=10)
    tmdb_rating: float | None = Field(None, ge=0, le=10)
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    code: str | None = None # Autogenerated if missing
    category_ids: list[int] | None = None
    page_ids: list[int] | None = None
    source_id: int | None = None

class MovieUpdate(BaseModel):
    title: str | None = None
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = Field(None, ge=0, le=10)
    tmdb_rating: float | None = Field(None, ge=0, le=10)
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    category_ids: list[int] | None = None
    page_ids: list[int] | None = None
    source_id: int | None = None

class MovieTranslationResponse(BaseModel):
    id: int
    movie_id: int
    language: str
    telegram_file_id: str | None = None
    storage_channel_message_id: int | None = None
    
    model_config = {"from_attributes": True}

class MovieResponse(BaseModel):
    id: int
    title: str
    original_title: str | None = None
    description: str | None = None
    imdb_rating: float | None = None
    tmdb_rating: float | None = None
    kinochi_rating: float | None = None
    kinochi_votes_count: int = 0
    genres: str | None = None
    cast: str | None = None
    director: str | None = None
    release_year: int | None = None
    runtime: int | None = None
    poster_url: str | None = None
    trailer_url: str | None = None
    code: str
    categories: list[CategoryResponse] = []
    pages: list[PageResponse] = []
    translations: list[MovieTranslationResponse] = []

    source_chat_id: int | None = None
    source_topic_id: int | None = None
    created_at: datetime | None = None

    @computed_field
    def source_link(self) -> str | None:
        if self.source_chat_id:
            chat_id_str = str(self.source_chat_id).replace("-100", "")
            if self.source_topic_id:
                return f"https://t.me/c/{chat_id_str}/{self.source_topic_id}"
            return f"https://t.me/c/{chat_id_str}"
        return None

    model_config = {"from_attributes": True}

class PaginatedMoviesResponse(BaseModel):
    items: list[MovieResponse]
    total: int


# ── Endpoints ────────────────────────────────────────────────────
@router.post("", response_model=MovieResponse, status_code=status.HTTP_201_CREATED)
@limiter.limit("10/minute")
async def create_movie(
    request: Request,
    movie_in: MovieCreate,
    service: MovieService = Depends(get_movie_service),
    db: AsyncSession = Depends(get_db_session),
    admin: dict = Depends(get_current_admin)
):
    """Create a new movie (Admin only)."""
    data = movie_in.model_dump()
    source_id = data.pop("source_id", None)
    
    if source_id:
        from app.infrastructure.db.repositories.source_repository import SourceRepository
        repo = SourceRepository(db)
        source = await repo.get_source_by_id(source_id)
        if source:
            data["source_chat_id"] = source.chat_id
            data["source_topic_id"] = source.topic_id
        else:
            raise HTTPException(status_code=400, detail="Manba (Source) topilmadi")
            
    if data.get("trailer_url"):
        data["trailer_url"] = await validate_and_normalize_trailer_url(data["trailer_url"])
            
    movie = await service.create_movie(**data)
    await delete_cache_pattern("cache:movies:*")
    return movie


@router.get("", response_model=PaginatedMoviesResponse)
@limiter.limit("100/minute")
async def list_movies(
    request: Request,
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    category_id: int | None = None,
    page_id: int | None = None,
    exclude_paged: bool = False,
    service: MovieService = Depends(get_movie_service)
):
    """List movies, optionally filtered by category (Public)."""
    cache_key = f"cache:movies:list:{skip}:{limit}:{category_id}:{page_id}:{exclude_paged}"
    cached = await get_cache(cache_key)
    if cached:
        return cached

    movies, total = await service.list_movies(skip=skip, limit=limit, category_id=category_id, page_id=page_id, exclude_paged=exclude_paged)
    
    # We must convert movie objects to dict before caching because Pydantic models aren't directly JSON serializable
    # Or rely on PaginatedMoviesResponse rendering them. Let's just use FastAPI's validation/serialization.
    # Actually, returning a dict directly works because FastAPI will serialize it. Let's just dump it.
    response_data = {"items": [m.model_dump(mode="json") if hasattr(m, "model_dump") else m for m in movies], "total": total}
    await set_cache(cache_key, response_data, 300)
    
    return {"items": movies, "total": total}


@router.get("/search", response_model=PaginatedMoviesResponse)
@limiter.limit("60/minute")
async def search_movies(
    request: Request,
    q: str = Query(..., min_length=2, description="Qidiruv matni"),
    skip: int = Query(0, ge=0),
    limit: int = Query(20, ge=1, le=100),
    service: MovieService = Depends(get_movie_service)
):
    """Search movies by title (Public)."""
    cache_key = f"cache:movies:search:{q}:{skip}:{limit}"
    cached = await get_cache(cache_key)
    if cached:
        return cached

    movies, total = await service.search_movies(title_query=q, skip=skip, limit=limit)
    response_data = {"items": [m.model_dump(mode="json") if hasattr(m, "model_dump") else m for m in movies], "total": total}
    await set_cache(cache_key, response_data, 300)
    
    return {"items": movies, "total": total}


@router.get("/code/{movie_code}", response_model=MovieResponse)
@limiter.limit("120/minute")
async def get_movie_by_code(
    request: Request,
    movie_code: str,
    service: MovieService = Depends(get_movie_service)
):
    """Get movie by unique code (Public / used by bot deep link)."""
    movie = await service.get_movie_by_code(movie_code)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found")
    return movie


@router.get("/by-source", response_model=MovieResponse)
@limiter.limit("120/minute")
async def get_movie_by_source(
    request: Request,
    chat_id: int,
    topic_id: int | None = None,
    service: MovieService = Depends(get_movie_service)
):
    """Get movie by source chat and topic (Used by Bot)."""
    movie = await service.get_movie_by_source(chat_id, topic_id)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found by source")
    return movie


@router.get("/{movie_id}", response_model=MovieResponse)
@limiter.limit("120/minute")
async def get_movie(
    request: Request,
    movie_id: int,
    service: MovieService = Depends(get_movie_service)
):
    """Get movie by ID (Public)."""
    movie = await service.get_movie(movie_id)
    if not movie:
        raise HTTPException(status_code=404, detail="Movie not found")
    return movie


@router.put("/{movie_id}", response_model=MovieResponse)
@limiter.limit("20/minute")
async def update_movie(
    request: Request,
    movie_id: int,
    movie_in: MovieUpdate,
    service: MovieService = Depends(get_movie_service),
    db: AsyncSession = Depends(get_db_session),
    admin: dict = Depends(get_current_admin)
):
    """Update a movie (Admin only)."""
    data = movie_in.model_dump(exclude_unset=True)
    
    has_source_id = "source_id" in movie_in.model_fields_set
    source_id = data.pop("source_id", None)
    
    if has_source_id:
        if source_id is None or source_id == "":
             data["source_chat_id"] = None
             data["source_topic_id"] = None
        else:
             from app.infrastructure.db.repositories.source_repository import SourceRepository
             repo = SourceRepository(db)
             source = await repo.get_source_by_id(source_id)
             if source:
                 data["source_chat_id"] = source.chat_id
                 data["source_topic_id"] = source.topic_id
             else:
                 raise HTTPException(status_code=400, detail="Manba (Source) topilmadi")
            
    if "trailer_url" in data and data["trailer_url"]:
        data["trailer_url"] = await validate_and_normalize_trailer_url(data["trailer_url"])
            
    updated_movie = await service.update_movie(movie_id, **data)
    if not updated_movie:
        raise HTTPException(status_code=404, detail="Movie not found")
        
    await delete_cache_pattern("cache:movies:*")
    return updated_movie


class UploadJobResponse(BaseModel):
    job_id: str
    status: str
    message: str


@router.post("/{movie_id}/upload-video", response_model=UploadJobResponse)
async def upload_movie_video(
    movie_id: int,
    request: Request,
    file: UploadFile = File(...),
    language: str = Form("Asosiy"),
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """
    Video faylni qabul qilib, orqa fonda Telegram'ga yuklaydi.
    Darhol job_id qaytaradi — frontend GET /upload-jobs/{job_id} orqali
    statusni kuzatib boradi.
    """
    if not file.content_type or not file.content_type.startswith("video/"):
        raise HTTPException(
            status_code=400,
            detail="Faqat video fayllar ruxsat etiladi (MIME turi video/* bo'lishi kerak)."
        )

    # ── Faylni vaqtinchalik joyga saqlash (tez, Render'ning 100s limitiga tushmaydi) ──
    # OS ni o'zining temp papkasi ishlatiladi
    suffix = os.path.splitext(file.filename or "video.mp4")[1] or ".mp4"
    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    tmp_path = tmp_file.name

    try:
        while True:
            chunk = await file.read(1024 * 1024)
            if not chunk:
                break
            tmp_file.write(chunk)
        tmp_file.close()
    except HTTPException:
        raise
    except Exception as e:
        try:
            tmp_file.close()
            os.remove(tmp_path)
        except Exception:
            pass
        logger.error(f"Error saving tmp file: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail="Faylni saqlashda xato.")

    # ── Background job yaratish ──
    job_id = await job_manager.create_job(meta={"movie_id": movie_id, "language": language})

    async def _background_upload():
        """Orqa fonda Telegram'ga yuklash va bazaga yozish."""
        await job_manager.set_processing(job_id, progress=5)
        try:
            async def _on_progress(pct: int):
                await job_manager.set_progress(job_id, pct)

            file_id, message_id = await telegram_client.send_video_to_storage(
                tmp_path=tmp_path,
                filename=file.filename or "video.mp4",
                mime_type=file.content_type or "video/mp4",
                on_progress=lambda p: asyncio.ensure_future(_on_progress(p)),
            )

            movie = await service.add_movie_translation(
                movie_id=movie_id,
                language=language,
                file_id=file_id,
                message_id=message_id
            )
            if not movie:
                await job_manager.set_failed(job_id, "Kino topilmadi (ID noto'g'ri).")
                return

            await job_manager.set_done(job_id, result={"movie_id": movie_id, "language": language})
        except Exception as e:
            err_msg = str(e)
            logger.error(f"Background upload failed for job {job_id}: {err_msg}", exc_info=True)
            await job_manager.set_failed(job_id, err_msg)
            # tmp faylni tozalash (telegram_client finally bloki ishlamagan bo'lsa)
            try:
                if os.path.exists(tmp_path):
                    os.remove(tmp_path)
            except Exception:
                pass

    # Orqa fonda ishga tushirish — HTTP response shu yerda qaytadi
    asyncio.create_task(_background_upload())
    await job_manager.cleanup_old_jobs()

    return UploadJobResponse(
        job_id=job_id,
        status=JobStatus.PROCESSING.value,
        message="Video qabul qilindi. Telegram'ga yuklanmoqda..."
    )


@router.get("/{movie_id}/upload-jobs/{job_id}")
async def get_upload_job_status(
    movie_id: int,
    job_id: str,
    admin: dict = Depends(get_current_admin)
):
    """Background upload job statusini tekshirish (polling uchun)."""
    job = await job_manager.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail="Job topilmadi.")
    return job


class LinkVideoRequest(BaseModel):
    message_id: int
    language: str = "Asosiy"
    source_url: str | None = None
    telegram_file_id: str | None = None

@router.post("/{movie_id}/link-video", response_model=MovieResponse)
async def link_movie_video(
    movie_id: int,
    request: LinkVideoRequest,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_admin_or_bot)
):
    """Link video for a movie from an existing message ID in the storage channel (Admin or Bot)."""
    try:
        movie = await service.link_movie_video_from_message(movie_id, request.message_id, request.language, source_url=request.source_url, telegram_file_id=request.telegram_file_id)
        if not movie:
            raise HTTPException(status_code=404, detail="Movie not found")
        return movie
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error in link_movie_video endpoint for movie {movie_id}: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="Xabardan video olishda kutilmagan xatolik.")

@router.delete("/translations/{translation_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_movie_translation(
    translation_id: int,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Delete a movie translation (Admin only)."""
    success = await service.delete_movie_translation(translation_id)
    if not success:
        raise HTTPException(status_code=404, detail="Translation not found")

@router.delete("/{movie_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_movie(
    movie_id: int,
    service: MovieService = Depends(get_movie_service),
    admin: dict = Depends(get_current_admin)
):
    """Delete a movie (Admin only)."""
    success = await service.delete_movie(movie_id)
    if not success:
        raise HTTPException(status_code=404, detail="Movie not found")
    await delete_cache_pattern("cache:movies:*")
