"""Add multi dubbing

Revision ID: 19a7009b0b0b
Revises: 940ed2f920d2
Create Date: 2026-07-12 16:15:26.212851
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19a7009b0b0b'
down_revision: Union[str, None] = '940ed2f920d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('storage_channel_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_translations_id'), 'movie_translations', ['id'], unique=False)
    op.create_index(op.f('ix_movie_translations_movie_id'), 'movie_translations', ['movie_id'], unique=False)
    op.create_table('episode_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('telegram_file_id', sa.String(length=255), nullable=True),
    sa.Column('storage_channel_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_translations_episode_id'), 'episode_translations', ['episode_id'], unique=False)
    op.create_index(op.f('ix_episode_translations_id'), 'episode_translations', ['id'], unique=False)
    op.drop_column('episodes', 'telegram_file_id')
    op.drop_column('episodes', 'storage_channel_message_id')
    op.drop_column('movies', 'telegram_file_id')
    op.drop_column('movies', 'storage_channel_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('storage_channel_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('telegram_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('storage_channel_message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('episodes', sa.Column('telegram_file_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_episode_translations_id'), table_name='episode_translations')
    op.drop_index(op.f('ix_episode_translations_episode_id'), table_name='episode_translations')
    op.drop_table('episode_translations')
    op.drop_index(op.f('ix_movie_translations_movie_id'), table_name='movie_translations')
    op.drop_index(op.f('ix_movie_translations_id'), table_name='movie_translations')
    op.drop_table('movie_translations')
    # ### end Alembic commands ###
