"""Add watch history table

Revision ID: 51e906b9692f
Revises: 66bfb6a20149
Create Date: 2026-08-02 13:33:34.310943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e906b9692f'
down_revision: Union[str, None] = '66bfb6a20149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(movie_id IS NOT NULL AND episode_id IS NULL) OR (movie_id IS NULL AND episode_id IS NOT NULL)', name='check_movie_or_episode'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_history_id'), 'watch_history', ['id'], unique=False)
    op.create_index(op.f('ix_watch_history_last_watched_at'), 'watch_history', ['last_watched_at'], unique=False)
    op.create_index(op.f('ix_watch_history_user_id'), 'watch_history', ['user_id'], unique=False)
    op.create_index('uix_watch_history_user_episode', 'watch_history', ['user_id', 'episode_id'], unique=True, postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.create_index('uix_watch_history_user_movie', 'watch_history', ['user_id', 'movie_id'], unique=True, postgresql_where=sa.text('movie_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_watch_history_user_movie', table_name='watch_history', postgresql_where=sa.text('movie_id IS NOT NULL'))
    op.drop_index('uix_watch_history_user_episode', table_name='watch_history', postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.drop_index(op.f('ix_watch_history_user_id'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_last_watched_at'), table_name='watch_history')
    op.drop_index(op.f('ix_watch_history_id'), table_name='watch_history')
    op.drop_table('watch_history')
    # ### end Alembic commands ###
