"""add reviews and kinochi rating

Revision ID: 55501de0fffd
Revises: eea5e498a8e6
Create Date: 2026-09-13 00:44:34.597628
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55501de0fffd'
down_revision: Union[str, None] = 'eea5e498a8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('movie_id IS NOT NULL OR series_id IS NOT NULL OR episode_id IS NOT NULL', name='check_target_item_not_null'),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='check_valid_rating_range'),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_episode_id'), 'reviews', ['episode_id'], unique=False)
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.create_index(op.f('ix_reviews_movie_id'), 'reviews', ['movie_id'], unique=False)
    op.create_index(op.f('ix_reviews_series_id'), 'reviews', ['series_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index('uix_review_user_episode', 'reviews', ['user_id', 'episode_id'], unique=True, postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.create_index('uix_review_user_movie', 'reviews', ['user_id', 'movie_id'], unique=True, postgresql_where=sa.text('movie_id IS NOT NULL'))
    op.create_index('uix_review_user_series', 'reviews', ['user_id', 'series_id'], unique=True, postgresql_where=sa.text('series_id IS NOT NULL'))
    op.add_column('movies', sa.Column('kinochi_rating', sa.Float(), nullable=True))
    op.add_column('movies', sa.Column('kinochi_votes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('series', sa.Column('kinochi_rating', sa.Float(), nullable=True))
    op.add_column('series', sa.Column('kinochi_votes_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'kinochi_votes_count')
    op.drop_column('series', 'kinochi_rating')
    op.drop_column('movies', 'kinochi_votes_count')
    op.drop_column('movies', 'kinochi_rating')
    op.drop_index('uix_review_user_series', table_name='reviews', postgresql_where=sa.text('series_id IS NOT NULL'))
    op.drop_index('uix_review_user_movie', table_name='reviews', postgresql_where=sa.text('movie_id IS NOT NULL'))
    op.drop_index('uix_review_user_episode', table_name='reviews', postgresql_where=sa.text('episode_id IS NOT NULL'))
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_series_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_movie_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_episode_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
