"""Add episode_count and duration

Revision ID: 5f880cb7b638
Revises: 19a7009b0b0b
Create Date: 2026-07-12 16:58:41.856140
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f880cb7b638'
down_revision: Union[str, None] = '19a7009b0b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('seasons', sa.Column('episode_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seasons', 'episode_count')
    op.drop_column('episodes', 'duration')
    # ### end Alembic commands ###
