"""Add trailer_url to SeriesModel

Revision ID: 66bfb6a20149
Revises: bd925cf13f66
Create Date: 2026-07-25 07:02:32.397079
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66bfb6a20149'
down_revision: Union[str, None] = 'bd925cf13f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('trailer_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'trailer_url')
    # ### end Alembic commands ###
