"""Add dynamic pages

Revision ID: 8e4e155f48db
Revises: 2fb109c075d0
Create Date: 2026-07-18 20:21:12.556883
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e4e155f48db'
down_revision: Union[str, None] = '2fb109c075d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # IF NOT EXISTS — jadval allaqachon mavjud bo'lsa xato chiqmasligi uchun
    op.execute("""
        CREATE TABLE IF NOT EXISTS pages (
            id SERIAL NOT NULL, 
            title VARCHAR(255) NOT NULL, 
            slug VARCHAR(255) NOT NULL, 
            is_active BOOLEAN NOT NULL, 
            created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
            updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL, 
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS ix_pages_id ON pages (id)")
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_pages_slug ON pages (slug)")

    op.execute("""
        CREATE TABLE IF NOT EXISTS page_movie (
            page_id INTEGER NOT NULL,
            movie_id INTEGER NOT NULL,
            PRIMARY KEY (page_id, movie_id),
            FOREIGN KEY(movie_id) REFERENCES movies (id) ON DELETE CASCADE,
            FOREIGN KEY(page_id) REFERENCES pages (id) ON DELETE CASCADE
        )
    """)

    op.execute("""
        CREATE TABLE IF NOT EXISTS page_series (
            page_id INTEGER NOT NULL,
            series_id INTEGER NOT NULL,
            PRIMARY KEY (page_id, series_id),
            FOREIGN KEY(page_id) REFERENCES pages (id) ON DELETE CASCADE,
            FOREIGN KEY(series_id) REFERENCES series (id) ON DELETE CASCADE
        )
    """)

    # series indekslari — IF NOT EXISTS bilan xavfsiz
    op.execute("CREATE INDEX IF NOT EXISTS ix_series_source_id ON series (source_id)")

    op.execute("""
        DO $$ BEGIN
            ALTER TABLE series_sources 
                ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE;
        EXCEPTION WHEN others THEN NULL;
        END $$;
    """)

    op.execute("CREATE INDEX IF NOT EXISTS ix_series_sources_chat_id ON series_sources (chat_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_series_sources_id ON series_sources (id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_series_sources_topic_id ON series_sources (topic_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_sources_topic_id'), table_name='series_sources')
    op.drop_index(op.f('ix_series_sources_id'), table_name='series_sources')
    op.drop_index(op.f('ix_series_sources_chat_id'), table_name='series_sources')
    op.alter_column('series_sources', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_series_source_id'), table_name='series')
    op.drop_table('page_series')
    op.drop_table('page_movie')
    op.drop_index(op.f('ix_pages_slug'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    # ### end Alembic commands ###
