"""add metadata to series

Revision ID: 940ed2f920d2
Revises: 930ed2f920d1
Create Date: 2026-07-12 12:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940ed2f920d2'
down_revision: Union[str, None] = '930ed2f920d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('imdb_rating', sa.Float(), nullable=True))
    op.add_column('series', sa.Column('release_year', sa.Integer(), nullable=True))
    op.add_column('series', sa.Column('director', sa.String(length=255), nullable=True))
    op.add_column('series', sa.Column('cast', sa.Text(), nullable=True))
    op.create_index(op.f('ix_series_release_year'), 'series', ['release_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_series_release_year'), table_name='series')
    op.drop_column('series', 'cast')
    op.drop_column('series', 'director')
    op.drop_column('series', 'release_year')
    op.drop_column('series', 'imdb_rating')
    # ### end Alembic commands ###
