"""Add status to series and seasons

Revision ID: bd925cf13f66
Revises: 8e4e155f48db
Create Date: 2026-07-25 05:11:25.935335
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd925cf13f66'
down_revision: Union[str, None] = '8e4e155f48db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('status', sa.String(length=50), server_default='ongoing', nullable=False))
    op.add_column('series', sa.Column('status', sa.String(length=50), server_default='ongoing', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'status')
    op.drop_column('seasons', 'status')
    # ### end Alembic commands ###
