"""rebuild_series_architecture

Revision ID: da3404d65ffd
Revises: 84dc4619e44e
Create Date: 2026-07-11 16:06:39.193115
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3404d65ffd'
down_revision: Union[str, None] = '84dc4619e44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('poster_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_series_id'), 'series', ['id'], unique=False)
    op.create_index(op.f('ix_series_title'), 'series', ['title'], unique=False)
    op.add_column('episodes', sa.Column('display_code', sa.String(length=50), nullable=False))
    op.drop_column('movies', 'is_series')
    op.add_column('seasons', sa.Column('series_id', sa.Integer(), nullable=False))
    op.add_column('seasons', sa.Column('title', sa.String(length=255), nullable=True))
    op.alter_column('seasons', 'description',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_seasons_movie_id'), table_name='seasons')
    op.create_index(op.f('ix_seasons_series_id'), 'seasons', ['series_id'], unique=False)
    op.drop_constraint(op.f('seasons_movie_id_fkey'), 'seasons', type_='foreignkey')
    op.create_foreign_key(None, 'seasons', 'series', ['series_id'], ['id'], ondelete='CASCADE')
    op.drop_column('seasons', 'movie_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seasons', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'seasons', type_='foreignkey')
    op.create_foreign_key(op.f('seasons_movie_id_fkey'), 'seasons', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_seasons_series_id'), table_name='seasons')
    op.create_index(op.f('ix_seasons_movie_id'), 'seasons', ['movie_id'], unique=False)
    op.alter_column('seasons', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_column('seasons', 'title')
    op.drop_column('seasons', 'series_id')
    op.add_column('movies', sa.Column('is_series', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('episodes', 'display_code')
    op.drop_index(op.f('ix_series_title'), table_name='series')
    op.drop_index(op.f('ix_series_id'), table_name='series')
    op.drop_table('series')
    # ### end Alembic commands ###
