"""MandatoryChannel repository interface."""
from typing import Sequence, Protocol
from app.domain.channels.entities import MandatoryChannel

class IMandatoryChannelRepository(Protocol):
    async def create(self, channel: MandatoryChannel) -> MandatoryChannel: ...
    async def get_by_id(self, id: int) -> MandatoryChannel | None: ...
    async def update(self, channel: MandatoryChannel) -> MandatoryChannel | None: ...
    async def delete(self, id: int) -> bool: ...
    async def list_active(self) -> Sequence[MandatoryChannel]: ...
    async def list_all(self, skip: int = 0, limit: int = 20) -> tuple[Sequence[MandatoryChannel], int]: ...
