import os
import sys
import json
import re
import urllib.request
import xml.etree.ElementTree as ET

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
OUTPUT_PATH = os.path.join(BASE_DIR, "scraper", "anitoob_catalog.json")

# 1. Fallback raw catalog from user's message
USER_RAW_LIST = """
1. [ Qahramon x (https://t.me/ANITOOBUZ_BOT?start=1) ]
2. [ Gleipnir (https://t.me/ANITOOBUZ_BOT?start=2) ]
3. [ Meni oyga olib ket 1-2-fasllar (https://t.me/ANITOOBUZ_BOT?start=3) ]
4. [ Metal alximik aka uka (https://t.me/ANITOOBUZ_BOT?start=4) ]
5. [ Platina yakun (https://t.me/ANITOOBUZ_BOT?start=5) ]
6. [ Inuyashiki (https://t.me/ANITOOBUZ_BOT?start=6) ]
7. [ Kelajak kundaligi (https://t.me/ANITOOBUZ_BOT?start=7) ]
8. [ Tabiat farzandi (https://t.me/ANITOOBUZ_BOT?start=8) ]
9. [ Hyouka (https://t.me/ANITOOBUZ_BOT?start=9) ]
10. [ Songi telba boss paydo boldi (https://t.me/ANITOOBUZ_BOT?start=10) ]
11. [ Arra odam arc (https://t.me/ANITOOBUZ_BOT?start=11) ]
12. [ Qilich sanati online ... 1 film (https://t.me/ANITOOBUZ_BOT?start=12) ]
13. [ Kaiju 8   1-2-fasllar (https://t.me/ANITOOBUZ_BOT?start=13) ]
14. [ Vampirlar ovchisi d (https://t.me/ANITOOBUZ_BOT?start=14) ]
15. [ Olim kundaligi (https://t.me/ANITOOBUZ_BOT?start=15) ]
16. [ Yozgi urushima tuneli (https://t.me/ANITOOBUZ_BOT?start=16) ]
17. [ Salom dunyo (https://t.me/ANITOOBUZ_BOT?start=17) ]
18. [ Nier avtomatlari (https://t.me/ANITOOBUZ_BOT?start=18) ]
19. [ Ozga dunyoda ruhsatsiz (https://t.me/ANITOOBUZ_BOT?start=19) ]
20. [ Iblislar qotili fanart film (https://t.me/ANITOOBUZ_BOT?start=20) ]
21. [ garoyib raqamli sirk (https://t.me/ANITOOBUZ_BOT?start=21) ]
22. [ Tomb rider qabr talonchisi (https://t.me/ANITOOBUZ_BOT?start=22) ]
23. [ Arcane (https://t.me/ANITOOBUZ_BOT?start=23) ]
24. [ Gachiakuta (https://t.me/ANITOOBUZ_BOT?start=24) ]
25. [ Jannat sarobi (https://t.me/ANITOOBUZ_BOT?start=25) ]
26. [ Bu ajoyib dunyo ... 2, 3-fasllar (https://t.me/ANITOOBUZ_BOT?start=26) ]
27. [ Yetti o'lim gunohlari (https://t.me/ANITOOBUZ_BOT?start=27) ]
28. [ Jodugarlar jangi s1 (https://t.me/ANITOOBUZ_BOT?start=28) ]
29. [ Jodugarlar jangi s2 (https://t.me/ANITOOBUZ_BOT?start=29) ]
30. [ Jodugarlar jangi s3 (https://t.me/ANITOOBUZ_BOT?start=30) ]
31. [ Hikaruning songi yozi (https://t.me/ANITOOBUZ_BOT?start=31) ]
32. [ Yolg'izlikda Daraja Ko'tarish (https://t.me/ANITOOBUZ_BOT?start=32) ]
33. [ Yolg'izlikda daraja kotarish (https://t.me/ANITOOBUZ_BOT?start=33) ]
34. [ Tungi boyqush kuyi s1 s2 (https://t.me/ANITOOBUZ_BOT?start=34) ]
35. [ Jahannam jannati (https://t.me/ANITOOBUZ_BOT?start=35) ]
36. [ Mushuk niqobi (https://t.me/ANITOOBUZ_BOT?start=36) ]
37. [ Sen bilan Supermarket ortida chekish (https://t.me/ANITOOBUZ_BOT?start=37) ]
38. [ Soyada kotarilish s1, s2 (https://t.me/ANITOOBUZ_BOT?start=38) ]
39. [ Yulduz farzandlari s1 s2 (https://t.me/ANITOOBUZ_BOT?start=39) ]
40. [ Chekishga mukasidan ketgan mushuk (https://t.me/ANITOOBUZ_BOT?start=40) ]
41. [ Iblislar qotili s1, ... 2 film (https://t.me/ANITOOBUZ_BOT?start=41) ]
42. [ akademiyaning birinchi raqamli ... qiladigan boʻldim (https://t.me/ANITOOBUZ_BOT?start=42) ]
43. [ Ovoz shakli (https://t.me/ANITOOBUZ_BOT?start=43) ]
44. [ Bleach (https://t.me/ANITOOBUZ_BOT?start=44) ]
45. [  ]
46. [ Bir soatlik qizcha (https://t.me/ANITOOBUZ_BOT?start=46) ]
47. [ Qora klever (https://t.me/ANITOOBUZ_BOT?start=47) ]
48. [ Jonli sana s1, ... + film (https://t.me/ANITOOBUZ_BOT?start=48) ]
49. [ TOKIO QASOSKORLARI s1, s2, s3 (https://t.me/ANITOOBUZ_BOT?start=49) ]
50. [ One Piece (https://t.me/ANITOOBUZ_BOT?start=50) ]
51. [ Ozga sayyoralik sevgilim (https://t.me/ANITOOBUZ_BOT?start=51) ]
52. [ Maxbus qahramon 9004 (https://t.me/ANITOOBUZ_BOT?start=52) ]
53. [ Men mavjud bolmagan shahar (https://t.me/ANITOOBUZ_BOT?start=53) ]
54. [ Re:ZERO - O'zga ... Noldan Boshlash (https://t.me/ANITOOBUZ_BOT?start=54) ]
55. [ Dandadan s1, s2 (https://t.me/ANITOOBUZ_BOT?start=55) ]
56. [ Jodugarlar jangi 0 film (https://t.me/ANITOOBUZ_BOT?start=56) ]
57. [ Hushboy gul viqor bilan gullaydi (https://t.me/ANITOOBUZ_BOT?start=57) ]
58. [ SHIBOYUGI: Stolga ovqat ... aylangan o‘yin (https://t.me/ANITOOBUZ_BOT?start=58) ]
59. [ Aprel yolgoni (https://t.me/ANITOOBUZ_BOT?start=59) ]
60. [ ZOMBI 100 (https://t.me/ANITOOBUZ_BOT?start=60) ]
61. [ Seni oshqozon osti bezingni yemoqchiman (https://t.me/ANITOOBUZ_BOT?start=61) ]
62. [ Yarim tunda yurak sadosi (https://t.me/ANITOOBUZ_BOT?start=62) ]
63. [ Frieren songi yolga kuzatuvchi (https://t.me/ANITOOBUZ_BOT?start=63) ]
64. [ Jahannam jannati s2 (https://t.me/ANITOOBUZ_BOT?start=64) ]
65. [ Avatar ang haqida afsona (https://t.me/ANITOOBUZ_BOT?start=65) ]
66. [ Kim meni malika qildi (https://t.me/ANITOOBUZ_BOT?start=66) ]
67. [ K-on (https://t.me/ANITOOBUZ_BOT?start=67) ]
68. [ Tatsuki fujimoto 17 26 (https://t.me/ANITOOBUZ_BOT?start=68) ]
69. [ Vinland haqida afsona s1, s2 (https://t.me/ANITOOBUZ_BOT?start=69) ]
70. [ Reinkarnatsiya barglari (https://t.me/ANITOOBUZ_BOT?start=70) ]
71. [ Tokio gul s1, ... s3, s4 (https://t.me/ANITOOBUZ_BOT?start=71) ]
72. [ Bezovta ruh hanako (https://t.me/ANITOOBUZ_BOT?start=72) ]
73. [ Yulduz farzandlari s3 (https://t.me/ANITOOBUZ_BOT?start=73) ]
74. [ Zanjirli qul (https://t.me/ANITOOBUZ_BOT?start=74) ]
75. [ Kaiju qiz (https://t.me/ANITOOBUZ_BOT?start=75) ]
76. [ Dororo (https://t.me/ANITOOBUZ_BOT?start=76) ]
77. [ Senga intilib s1, s2, s3 (https://t.me/ANITOOBUZ_BOT?start=77) ]
78. [ Naruto (1-fasil) (https://t.me/ANITOOBUZ_BOT?start=78) ]
79. [ Spiral | Uzumaki (https://t.me/ANITOOBUZ_BOT?start=79) ]
80. [ Mob psixo 100 (https://t.me/ANITOOBUZ_BOT?start=80) ]
81. [ Sen va men ... qarama qarshimiz (https://t.me/ANITOOBUZ_BOT?start=81) ]
82. [ Kok zindon s1, s2 (https://t.me/ANITOOBUZ_BOT?start=82) ]
83. [ Kaya - chan (https://t.me/ANITOOBUZ_BOT?start=83) ]
84. [ Tokyodagi terrorchilik (https://t.me/ANITOOBUZ_BOT?start=84) ]
85. [ Tajribasiz sen va men (https://t.me/ANITOOBUZ_BOT?start=85) ]
86. [ Shamol kotariladi (https://t.me/ANITOOBUZ_BOT?start=86) ]
87. [ Yugurening abadiyligi (https://t.me/ANITOOBUZ_BOT?start=87) ]
88. [ Sen uchun olmas ... s2, s3 (https://t.me/ANITOOBUZ_BOT?start=88) ]
89. [ Franksdagi sevgilim (https://t.me/ANITOOBUZ_BOT?start=89) ]
90. [ Naruto qonli qamoqxona 8-film (https://t.me/ANITOOBUZ_BOT?start=90) ]
91. [ Oltin vaqt (https://t.me/ANITOOBUZ_BOT?start=91) ]
92. [ Ragnarok rekordi s1 s2 s3 (https://t.me/ANITOOBUZ_BOT?start=92) ]
93. [ Miss Kobayashining ajdarho hizmatkorlari (https://t.me/ANITOOBUZ_BOT?start=93) ]
94. [ Aura: Koga Maryuining Soʻngi Jangi (https://t.me/ANITOOBUZ_BOT?start=94) ]
95. [ Fate : soxta muqaddas urush (https://t.me/ANITOOBUZ_BOT?start=95) ]
96. [ Sharlotta (https://t.me/ANITOOBUZ_BOT?start=96) ]
97. [ Tubsizlik farzandi (https://t.me/ANITOOBUZ_BOT?start=97) ]
98. [ Zanjirlangan qul s2 (https://t.me/ANITOOBUZ_BOT?start=98) ]
99. [ Dragon raja s1 (https://t.me/ANITOOBUZ_BOT?start=99) ]
100. [ Titanlar hujumi s1, ... s3, s4 (https://t.me/ANITOOBUZ_BOT?start=100) ]
101. [ Iblislar maktabiga xush ... iruma kun (https://t.me/ANITOOBUZ_BOT?start=101) ]
102. [ Xayr don glees (https://t.me/ANITOOBUZ_BOT?start=102) ]
103. [ Arra odam s1 (https://t.me/ANITOOBUZ_BOT?start=103) ]
104. [ Lideyl dunyosi (https://t.me/ANITOOBUZ_BOT?start=104) ]
105. [ Triniti : yetti sehrgar (https://t.me/ANITOOBUZ_BOT?start=105) ]
106. [ 91 kun (https://t.me/ANITOOBUZ_BOT?start=106) ]
107. [ Lookism (https://t.me/ANITOOBUZ_BOT?start=107) ]
108. [ Ozga dunyo fermerlik hayotim (https://t.me/ANITOOBUZ_BOT?start=108) ]
109. [ Monster (https://t.me/ANITOOBUZ_BOT?start=109) ]
110. [ Sehr va mushaklar s1, s2 (https://t.me/ANITOOBUZ_BOT?start=110) ]
111. [ Fate : taqdir jang kechasi (https://t.me/ANITOOBUZ_BOT?start=111) ]
112. [ Bir zarbli odam s1 s2 (https://t.me/ANITOOBUZ_BOT?start=112) ]
113. [ Medal sohibi (https://t.me/ANITOOBUZ_BOT?start=113) ]
114. [ Horomiya s1 s2 (https://t.me/ANITOOBUZ_BOT?start=114) ]
115. [ Harobalar qirolligi (https://t.me/ANITOOBUZ_BOT?start=115) ]
116. [ Berserk s1 s2 s3 (https://t.me/ANITOOBUZ_BOT?start=116) ]
117. [ Gersogning shartnomali qalliği (https://t.me/ANITOOBUZ_BOT?start=117) ]
118. [ Tankchi qizlar (https://t.me/ANITOOBUZ_BOT?start=118) ]
119. [ Monogatari (https://t.me/ANITOOBUZ_BOT?start=119) ]
120. [ Yonar yulduzlar qabri (https://t.me/ANITOOBUZ_BOT?start=120) ]
121. [ Qayta tuğilgan aristokratning ... kòrilmagan sarguzashtlari (https://t.me/ANITOOBUZ_BOT?start=121) ]
122. [ Qayta tuğilgan aristokratning ... kòrilmagan sarguzashtlari (https://t.me/ANITOOBUZ_BOT?start=122) ]
123. [ Oyga sayohat (https://t.me/ANITOOBUZ_BOT?start=123) ]
124. [ Takopining ilk gunohi (https://t.me/ANITOOBUZ_BOT?start=124) ]
125. [ Talonchi (https://t.me/ANITOOBUZ_BOT?start=125) ]
126. [ Yoz arvohi (https://t.me/ANITOOBUZ_BOT?start=126) ]
127. [ Seni juda juda ... s1, s2 (https://t.me/ANITOOBUZ_BOT?start=127) ]
128. [ Junjito kolleksiyasi s1 s2 (https://t.me/ANITOOBUZ_BOT?start=128) ]
129. [ Code geass (https://t.me/ANITOOBUZ_BOT?start=129) ]
130. [ Juda ham yoqimtoy mabuda (https://t.me/ANITOOBUZ_BOT?start=130) ]
131. [ Jangchi xoroz (https://t.me/ANITOOBUZ_BOT?start=131) ]
132. [ Ozga dunyoda oilalik boldim (https://t.me/ANITOOBUZ_BOT?start=132) ]
133. [ Shilliq sifatida qayta tuğuldim (https://t.me/ANITOOBUZ_BOT?start=133) ]
134. [ Shilliq sifatida qayta tuğilganim haqida (https://t.me/ANITOOBUZ_BOT?start=134) ]
135. [ Kók bahor sayohati (https://t.me/ANITOOBUZ_BOT?start=135) ]
136. [ Gersogning qiziga shaxsiy óqituvchi bòldim (https://t.me/ANITOOBUZ_BOT?start=136) ]
137. [ Ikkimiz yolğizlikda (https://t.me/ANITOOBUZ_BOT?start=137) ]
138. [ Oltin rangdagi vermeil (https://t.me/ANITOOBUZ_BOT?start=138) ]
139. [ Grancrest afsonasi (https://t.me/ANITOOBUZ_BOT?start=139) ]
140. [ Chegara ortida (https://t.me/ANITOOBUZ_BOT?start=140) ]
141. [ Violet evergarden 13 ... 1 film (https://t.me/ANITOOBUZ_BOT?start=141) ]
142. [ Cyber punk | cyber qochqin (https://t.me/ANITOOBUZ_BOT?start=142) ]
143. [ Qòshni farishta (https://t.me/ANITOOBUZ_BOT?start=143) ]
144. [ Qòshni farishta S1 (https://t.me/ANITOOBUZ_BOT?start=144) ]
145. [ Viktoria : tayoq va qilich (https://t.me/ANITOOBUZ_BOT?start=145) ]
146. [ Kaguya honim sevgi ... s2, s3 (https://t.me/ANITOOBUZ_BOT?start=146) ]
147. [ Alya bazan men ... karashma qiladi (https://t.me/ANITOOBUZ_BOT?start=147) ]
148. [ Bleach ming yillik qonli urush (https://t.me/ANITOOBUZ_BOT?start=148) ]
149. [ Bo'sani jalb etib (https://t.me/ANITOOBUZ_BOT?start=149) ]
150. [ Uysiz mabud (https://t.me/ANITOOBUZ_BOT?start=150) ]
151. [ Yolğiz qahramon ming hunar egasi (https://t.me/ANITOOBUZ_BOT?start=151) ]
152. [ Sehrgar qizning ustahonasi (https://t.me/ANITOOBUZ_BOT?start=152) ]
153. [ Ikki òt orasida (https://t.me/ANITOOBUZ_BOT?start=153) ]
154. [ Po'lat qaladagi kabaneri (https://t.me/ANITOOBUZ_BOT?start=154) ]
155. [ Zaharli nikoh (https://t.me/ANITOOBUZ_BOT?start=155) ]
156. [ Vaxshiylar malikasi (https://t.me/ANITOOBUZ_BOT?start=156) ]
157. [ Qo'shni farishta s2 (https://t.me/ANITOOBUZ_BOT?start=157) ]
158. [ Jonli efirdagi jang (https://t.me/ANITOOBUZ_BOT?start=158) ]
159. [ Uch mikadona opa singillar (https://t.me/ANITOOBUZ_BOT?start=159) ]
160. [ Dragon ball z (https://t.me/ANITOOBUZ_BOT?start=160) ]
161. [ Re:zero real hayotni ... boshlab 4-fasl (https://t.me/ANITOOBUZ_BOT?start=161) ]
162. [ Qotil akame (https://t.me/ANITOOBUZ_BOT?start=162) ]
163. [ Another (https://t.me/ANITOOBUZ_BOT?start=163) ]
164. [ Moviy qotil (https://t.me/ANITOOBUZ_BOT?start=164) ]
165. [ K project (https://t.me/ANITOOBUZ_BOT?start=165) ]
166. [ Qon-C (https://t.me/ANITOOBUZ_BOT?start=166) ]
167. [ Cholning VRMMO o'yinidagi hayoti (https://t.me/ANITOOBUZ_BOT?start=167) ]
168. [ Dragon ball (https://t.me/ANITOOBUZ_BOT?start=168) ]
169. [ Taomlar jangi (https://t.me/ANITOOBUZ_BOT?start=169) ]
170. [ O'lim Farishtasi (https://t.me/ANITOOBUZ_BOT?start=170) ]
171. [ Oltin vermeil (https://t.me/ANITOOBUZ_BOT?start=171) ]
172. [ Iblislar ham yiglaydi (https://t.me/ANITOOBUZ_BOT?start=172) ]
173. [ Dunyodagi eng zo‘r qotil (https://t.me/ANITOOBUZ_BOT?start=173) ]
174. [ Elita sinfi 4-fasl (https://t.me/ANITOOBUZ_BOT?start=174) ]
175. [ Mening baxtli turmushim (https://t.me/ANITOOBUZ_BOT?start=175) ]
176. [ Oq mushuk loyihasi (https://t.me/ANITOOBUZ_BOT?start=176) ]
177. [ Saroydan quvilgan sehrgar ... bo‘lishga intiladi (https://t.me/ANITOOBUZ_BOT?start=177) ]
178. [ Boshqa dunyo bir ... dosh berolmaydi (https://t.me/ANITOOBUZ_BOT?start=178) ]
179. [ Davolovchi qahramon (https://t.me/ANITOOBUZ_BOT?start=179) ]
180. [ Oxirgi bir narsani so'rasam maylimi? (https://t.me/ANITOOBUZ_BOT?start=180) ]
181. [ Kaguya xonim sevgi bu jang (https://t.me/ANITOOBUZ_BOT?start=181) ]
182. [ Sen uchun O'lmas 1-Fasl (https://t.me/ANITOOBUZ_BOT?start=182) ]
183. [ Po'lat qal'adagi kabaneri (https://t.me/ANITOOBUZ_BOT?start=183) ]
184. [ 86 (https://t.me/ANITOOBUZ_BOT?start=184) ]
185. [ Tusundera bolalari (https://t.me/ANITOOBUZ_BOT?start=185) ]
186. [ Men dunyodagi eng ... bo'lishni xoxlayman (https://t.me/ANITOOBUZ_BOT?start=186) ]
187. [ Badarg'a qilingan qahramon (https://t.me/ANITOOBUZ_BOT?start=187) ]
188. [ Dunyo hali ham go'zal (https://t.me/ANITOOBUZ_BOT?start=188) ]
189. [ Real dunyodan haqiqiyroq o'yin (https://t.me/ANITOOBUZ_BOT?start=189) ]
190. [ Tomadachi Game (https://t.me/ANITOOBUZ_BOT?start=190) ]
191. [ Bu chinni qiz ... sevib qoldi (https://t.me/ANITOOBUZ_BOT?start=191) ]
192. [ Iblislar maktabiga xush ... kun 4-fasl (https://t.me/ANITOOBUZ_BOT?start=192) ]
193. [ Qayta tugʻilgan aristokratning ... ko'rilmagan sarguzashtlari (https://t.me/ANITOOBUZ_BOT?start=193) ]
194. [ Xarobalar Qiroligi (https://t.me/ANITOOBUZ_BOT?start=194) ]
195. [ Sevgining ilmiy isboti (https://t.me/ANITOOBUZ_BOT?start=195) ]
196. [ Oʻzga dunyoda jodugarni himoya qildim (https://t.me/ANITOOBUZ_BOT?start=196) ]
197. [ O'lim boshqaruvchisi (https://t.me/ANITOOBUZ_BOT?start=197) ]
198. [ Soya olami (https://t.me/ANITOOBUZ_BOT?start=198) ]
199. [ Ozga dunyoda fermerlik ... 2 fasl (https://t.me/ANITOOBUZ_BOT?start=199) ]
200. [ Sakamoto kunlari (https://t.me/ANITOOBUZ_BOT?start=200) ]
201. [ Arifureta (https://t.me/ANITOOBUZ_BOT?start=201) ]
202. [ Egzartist boshqa dunyoda ... bo'lishga intiladi (https://t.me/ANITOOBUZ_BOT?start=202) ]
203. [ Titanlar Hujumi (https://t.me/ANITOOBUZ_BOT?start=203) ]
204. [ Arra Odam (https://t.me/ANITOOBUZ_BOT?start=204) ]
205. [ Dunyodagi oxirgi erkak (https://t.me/ANITOOBUZ_BOT?start=205) ]
206. [ Naruto 2 Fasl (https://t.me/ANITOOBUZ_BOT?start=206) ]
207. [ Wind breaker shamolni boʻysindirish (https://t.me/ANITOOBUZ_BOT?start=207) ]
208. [ Sehrgar qizning ustaxonasi (https://t.me/ANITOOBUZ_BOT?start=208) ]
209. [ Ablah (https://t.me/ANITOOBUZ_BOT?start=209) ]
210. [ Qora Qirolning Qaytishi (https://t.me/ANITOOBUZ_BOT?start=210) ]
211. [ Suv sehirgari (https://t.me/ANITOOBUZ_BOT?start=211) ]
212. [ Orqaga qara (https://t.me/ANITOOBUZ_BOT?start=212) ]
213. [ Olik akkaunt (https://t.me/ANITOOBUZ_BOT?start=213) ]
214. [ Whitch watch | sehrli soat (https://t.me/ANITOOBUZ_BOT?start=214) ]
215. [ Shamolni boʻysindirish (https://t.me/ANITOOBUZ_BOT?start=215) ]
216. [ Iblislar bazmi (https://t.me/ANITOOBUZ_BOT?start=216) ]
217. [ Tayoq va qilich s2 (https://t.me/ANITOOBUZ_BOT?start=217) ]
218. [ shilliq sifatida qayta ... haqida 4-fasl (https://t.me/ANITOOBUZ_BOT?start=218) ]
219. [ Orin almashganlar (https://t.me/ANITOOBUZ_BOT?start=219) ]
220. [ besh kelin (https://t.me/ANITOOBUZ_BOT?start=220) ]
221. [ Baki (https://t.me/ANITOOBUZ_BOT?start=221) ]
222. [ Shiunji oilasining farzandlari (https://t.me/ANITOOBUZ_BOT?start=222) ]
223. [ Laputa samoviy saroy (https://t.me/ANITOOBUZ_BOT?start=223) ]
224. [ Yozakura oilasi 2-fasl (https://t.me/ANITOOBUZ_BOT?start=224) ]
225. [ SEVGI OʻLIM VA  ROBITLAR (https://t.me/ANITOOBUZ_BOT?start=225) ]
226. [ SEVGI OʻLIM VA ROBITLAR (https://t.me/ANITOOBUZ_BOT?start=226) ]
227. [ Mening Qahramonlik Akademiyam (https://t.me/ANITOOBUZ_BOT?start=227) ]
228. [ Mening Qahramonlik Akademiyam (https://t.me/ANITOOBUZ_BOT?start=228) ]
229. [ Mening Qahramonlik Akademiyam (https://t.me/ANITOOBUZ_BOT?start=229) ]
230. [ Mening qahramonlik akademiyam (https://t.me/ANITOOBUZ_BOT?start=230) ]
231. [ Mening Qahramonlik akademiyam (https://t.me/ANITOOBUZ_BOT?start=231) ]
232. [ Piter grill (https://t.me/ANITOOBUZ_BOT?start=232) ]
233. [ Mo'jizaviy tuhum ustivorligi (https://t.me/ANITOOBUZ_BOT?start=233) ]
234. [ Mening Qahramonlik akademiyam (https://t.me/ANITOOBUZ_BOT?start=234) ]
235. [ Sirlar hukmdori (https://t.me/ANITOOBUZ_BOT?start=235) ]
236. [ Sening isming (https://t.me/ANITOOBUZ_BOT?start=236) ]
237. [ Ertaga joe s1 s2 (https://t.me/ANITOOBUZ_BOT?start=237) ]
238. [ Shteyn darovozasi (https://t.me/ANITOOBUZ_BOT?start=238) ]
239. [ 🎞️| Men kuchsiz ... yoq qilaman (https://t.me/ANITOOBUZ_BOT?start=239) ]
240. [ Sinfsiz qahramon (https://t.me/ANITOOBUZ_BOT?start=240) ]
241. [ Mabud minorasi (https://t.me/ANITOOBUZ_BOT?start=241) ]
242. [ Sevgida yutqizgan qizlar namuncha kop (https://t.me/ANITOOBUZ_BOT?start=242) ]
243. [ Bir xonada quyosh va farishta (https://t.me/ANITOOBUZ_BOT?start=243) ]
244. [ Men sinfimdagi ikkinchi ... dost boldim (https://t.me/ANITOOBUZ_BOT?start=244) ]
245. [ Yaponiya uch saltanati (https://t.me/ANITOOBUZ_BOT?start=245) ]
246. [ Partiyasidan quvilgan tabib ... eng kuchli (https://t.me/ANITOOBUZ_BOT?start=246) ]
247. [ Dmc iblislar ham yiglaydi (https://t.me/ANITOOBUZ_BOT?start=247) ]
248. [ Seni sevadigan yagona inson (https://t.me/ANITOOBUZ_BOT?start=248) ]
249. [ Xotinimning his tuyg'usi yo'q (https://t.me/ANITOOBUZ_BOT?start=249) ]
250. [ Mabud minorasi (https://t.me/ANITOOBUZ_BOT?start=250) ]
251. [ Ovchi x Ovchi (https://t.me/ANITOOBUZ_BOT?start=251) ]
252. [ Ragna crimson (https://t.me/ANITOOBUZ_BOT?start=252) ]
253. [ Chunibyo (https://t.me/ANITOOBUZ_BOT?start=253) ]
254. [ Skelet ritser (https://t.me/ANITOOBUZ_BOT?start=254) ]
255. [ Elf rafiqamni qanday sevishim mumkin (https://t.me/ANITOOBUZ_BOT?start=255) ]
256. [ O'ta ehtiyotkor o'lmas qahramon (https://t.me/ANITOOBUZ_BOT?start=256) ]
257. [ Tanyaning urush yilnomalari (https://t.me/ANITOOBUZ_BOT?start=257) ]
258. [ Another (https://t.me/ANITOOBUZ_BOT?start=258) ]
259. [ Meni baxtlik turmushim (https://t.me/ANITOOBUZ_BOT?start=259) ]
260. [ Yurar qal'a (https://t.me/ANITOOBUZ_BOT?start=260) ]
261. [ Stein darvozasi (https://t.me/ANITOOBUZ_BOT?start=261) ]
262. [ Gabriel maktabni tashlayapti (https://t.me/ANITOOBUZ_BOT?start=262) ]
263. [ Sehrgarlar Atelyasi (https://t.me/ANITOOBUZ_BOT?start=263) ]
264. [ Boruto (https://t.me/ANITOOBUZ_BOT?start=264) ]
265. [ Ogʻriq Rishtasi (https://t.me/ANITOOBUZ_BOT?start=265) ]
266. [  ]
267. [ Online o'yindagi qizing ... deb o'yladingmi? (https://t.me/ANITOOBUZ_BOT?start=267) ]
268. [ Bolalikdagi do‘stlar bilan ... mumkin emas (https://t.me/ANITOOBUZ_BOT?start=268) ]
269. [ ifureta: Dunyodagi eng kuchli hunarmand (https://t.me/ANITOOBUZ_BOT?start=269) ]
270. [  ]
271. [ Tearmoon Impirya hikoyasi (https://t.me/ANITOOBUZ_BOT?start=271) ]
272. [ Amagami oilasi bn nikoh rishtalari (https://t.me/ANITOOBUZ_BOT?start=272) ]
273. [ Velzevul (https://t.me/ANITOOBUZ_BOT?start=273) ]
274. [ Odobga chaqiruvchi va beodob (https://t.me/ANITOOBUZ_BOT?start=274) ]
275. [ Zindonda qizlar bilan uchrashish yomonmi (https://t.me/ANITOOBUZ_BOT?start=275) ]
276. [ Internat maktabidagi Julleta (https://t.me/ANITOOBUZ_BOT?start=276) ]
277. [ Voleybol: Haikyuu (https://t.me/ANITOOBUZ_BOT?start=277) ]
278. [ Ma’lum bo‘lishicha, eng ... baholovchi ekan (https://t.me/ANITOOBUZ_BOT?start=278) ]
279. [ Sakson olti (https://t.me/ANITOOBUZ_BOT?start=279) ]
280. [ Sinfsiz qahramon (https://t.me/ANITOOBUZ_BOT?start=280) ]
281. [ Songi serafim (https://t.me/ANITOOBUZ_BOT?start=281) ]
282. [ Kosmic malika kaguya (https://t.me/ANITOOBUZ_BOT?start=282) ]
283. [ Opamning sodiq yigitiga unashtirildim (https://t.me/ANITOOBUZ_BOT?start=283) ]
284. [ Doktor stone (https://t.me/ANITOOBUZ_BOT?start=284) ]
285. [ 999-darajali qishloqi (https://t.me/ANITOOBUZ_BOT?start=285) ]
286. [ Omadsizning qayta tugilishi (https://t.me/ANITOOBUZ_BOT?start=286) ]
287. [ Kumush qirolning qayta tug\'ilishi (https://t.me/ANITOOBUZ_BOT?start=287) ]
288. [ Ruh yilnomalari (https://t.me/ANITOOBUZ_BOT?start=288) ]
289. [ Saiki Kusuoning dahshatli hayoti (https://t.me/ANITOOBUZ_BOT?start=289) ]
290. [ Qora qirolning qaytishi (https://t.me/ANITOOBUZ_BOT?start=290) ]
291. [ O\'yinsiz hayot yo\'q (https://t.me/ANITOOBUZ_BOT?start=291) ]
292. [ Ochkoz berserk (https://t.me/ANITOOBUZ_BOT?start=292) ]
293. [ Coraline (https://t.me/ANITOOBUZ_BOT?start=293) ]
294. [ Castlenavia (https://t.me/ANITOOBUZ_BOT?start=294) ]
295. [ Rik va morti (https://t.me/ANITOOBUZ_BOT?start=295) ]
296. [ Naruto 9- film ninzalik yoli (https://t.me/ANITOOBUZ_BOT?start=296) ]
297. [ Soyalar olami iblislari (https://t.me/ANITOOBUZ_BOT?start=297) ]
298. [ Yettinchi shahzoda sifatida qayta tug\'ildim (https://t.me/ANITOOBUZ_BOT?start=298) ]
299. [ Olmas sarguzashtchi (https://t.me/ANITOOBUZ_BOT?start=299) ]
300. [ Jodugar chodiri (https://t.me/ANITOOBUZ_BOT?start=300) ]
301. [ Omadsiz tirik murda (https://t.me/ANITOOBUZ_BOT?start=301) ]
302. [ Ishsiz iblislar lordi (https://t.me/ANITOOBUZ_BOT?start=302) ]
303. [ Josus x oilasi (https://t.me/ANITOOBUZ_BOT?start=303) ]
304. [ Surgun qilingan ogʻir ... daraja koʻtarish (https://t.me/ANITOOBUZ_BOT?start=304) ]
305. [ Hechnimadan habari yoq ustaning hayoti (https://t.me/ANITOOBUZ_BOT?start=305) ]
306. [ Qalqon qahramoni (https://t.me/ANITOOBUZ_BOT?start=306) ]
307. [ Shokolad kupidon (https://t.me/ANITOOBUZ_BOT?start=307) ]
"""

catalog = {}

# Parse user raw list first
for line in USER_RAW_LIST.strip().splitlines():
    line = line.strip()
    m = re.match(r"^(\d+)\.\s*\[\s*(.*?)\s*\((https://t\.me/ANITOOBUZ_BOT\?start=(\d+))\)\s*\]", line)
    if m:
        c_num = m.group(1)
        title = m.group(2).strip()
        url = m.group(3).strip()
        code = m.group(4).strip()
        catalog[code] = {
            "code": code,
            "title": title or f"Anime #{code}",
            "url": url,
            "poster_url": None
        }

print(f"Parsed {len(catalog)} from user's message.")

# Now enrich from sitemap.xml
try:
    req = urllib.request.Request("https://bot.anitoobtv.uz/sitemap.xml", headers={"User-Agent": "Mozilla/5.0"})
    raw = urllib.request.urlopen(req, timeout=12).read()
    root = ET.fromstring(raw)
    ns = {"s": "http://www.sitemaps.org/schemas/sitemap/0.9", "img": "http://www.google.com/schemas/sitemap-image/1.1"}
    sitemap_count = 0
    for u in root.findall("s:url", ns):
        loc = u.find("s:loc", ns).text if u.find("s:loc", ns) is not None else ""
        m = re.search(r"anime=(\d+)", loc)
        if not m:
            continue
        code = m.group(1)
        sitemap_count += 1
        img_elem = u.find("img:image", ns)
        img_title = img_elem.find("img:title", ns).text if img_elem is not None and img_elem.find("img:title", ns) is not None else ""
        img_loc = img_elem.find("img:loc", ns).text if img_elem is not None and img_elem.find("img:loc", ns) is not None else ""

        clean_t = re.sub(r"\s+o['ʼ`]zbek\s+tilida.*$", "", img_title, flags=re.IGNORECASE).strip()
        
        if code in catalog:
            if not catalog[code]["title"] or catalog[code]["title"].endswith("..."):
                catalog[code]["title"] = clean_t or catalog[code]["title"]
            catalog[code]["poster_url"] = img_loc or catalog[code]["poster_url"]
            catalog[code]["site_url"] = loc
        else:
            catalog[code] = {
                "code": code,
                "title": clean_t or f"Anime #{code}",
                "url": f"https://t.me/ANITOOBUZ_BOT?start={code}",
                "poster_url": img_loc,
                "site_url": loc
            }
    print(f"Enriched {sitemap_count} items from sitemap.xml. Total catalog size: {len(catalog)}")
except Exception as e:
    print(f"Error fetching sitemap.xml: {e}")

# Save to scraper/anitoob_catalog.json
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(catalog, f, ensure_ascii=False, indent=2)

print(f"Successfully written {len(catalog)} items to {OUTPUT_PATH}")
