"""User repository interface."""
from typing import Sequence, Protocol
from app.domain.users.entities import User

class IUserRepository(Protocol):
    async def create_or_update(self, user: User) -> User: ...
    async def get_by_telegram_id(self, telegram_id: int) -> User | None: ...
    async def list_users(self, skip: int = 0, limit: int = 20, is_banned: bool | None = None) -> tuple[Sequence[User], int]: ...
    async def set_ban_status(self, telegram_id: int, is_banned: bool) -> bool: ...
